### PR TITLE
Import perltidy that was used on project

### PR DESCRIPTION
**Pull request by exodist**
This is the perltidy I used when I wrote the project.

### CODE REVIEW

**Comment by RsrchBoy** [comment]
How are you invoking this?  If we're going to be applying this to every file we probably should have a helper script, as well as author tests.

**Comment by exodist** [comment]
I use some vim integration to tidy files as I work on them. There are no general tools I can import, we would have to write them.

**Comment by RsrchBoy** [comment]
Well, for tests there are things like: https://metacpan.org/pod/Test::PerlTidy

If we don't want to test or have an assist tools, then I'm fine with just including the perltidyrc so long as there's an expectation that any noted variances can be done via cleanup commits and will not serve as blockers to functional PR's.

**Comment by exodist** [comment]
I personally won't block on reviews that fix anything that violates the perltidy rules.

**Comment by RsrchBoy** [comment]
Ok, so, after our offline conversation:

* at some point soon we're going to add an assist script, and automated author tests via Test::PerlTidy (or the equivalent); and
* a CI job to run tests automagically and report feedback here

*Until then, perltidy violations will not be used as a basis for rejecting functional pull requests.*

...though this does not bar anyone from declining to merge something with syntax that defies common sense, generally does not comport with expectations, or meets the threshold for a charge of "uncommon stupidity", as used in Kim Harrison's novels.

**Pull request merged**
